context('Easypos', () =>{
    
        beforeEach(function () {
        cy.visit('https://h1111.oteldensatinal.com/Hotel').viewport(1200,729)
    })
    Cypress.Commands.add('tusTikla',(ara)=>{
        cy.get('button')
            .contains(ara)
                .click({force:true})
                    .wait(500)
     })
     Cypress.Commands.add('OdaSec',(OdaTur)=>{
        cy.get('body')
            .contains(OdaTur,{timeout:60000})
                .parent()
                    .parent()
                        .parent()
                            .parent()
                                .find('button',{timeout:60000})
                                    .contains('Satın Al')
                                        .click({force:true})
    })
    Cypress.Commands.add('FieldWrapperDoldur',(kutuad,doldurad)=>{
        cy.get('.mat-form-field-wrapper')
            .contains(kutuad)
                .parent()
                    .parent()
                        .parent()
                            .find('input')
                                .click({force:true})
                                    .wait(400)
                                        .type(doldurad)
     })
     Cypress.Commands.add('FieldInfixDoldur',(kutuad,doldurad)=>{
        cy.get('.mat-form-field-infix')
            .contains(kutuad)
                .parent()
                    .parent()
                        .parent()
                            .find('textarea')
                                .type(doldurad)
     })
     Cypress.Commands.add('AdresBilgileri',(ad,soyad,telefon,eposta,sehir,zipkod,adres,not)=>{
        cy.get('mat-step-header')
            .contains('İletişim Bilgileri',{timeout:60000})
                .FieldWrapperDoldur('Ad',ad)
                    .FieldWrapperDoldur('Soyad',soyad)
                        .FieldWrapperDoldur('Telefon',telefon)
                            .FieldWrapperDoldur('Eposta',eposta)
                                .FieldWrapperDoldur('Şehir',sehir)
                                    .FieldWrapperDoldur('Zip Kod',zipkod)
                                        .FieldInfixDoldur('Adres',adres)
                                            .FieldInfixDoldur('Ekstra Not',not)
                                                .tusTikla('İleri')
     })
    it('Otelsatinalinir', () => {
        cy.tusTikla('Oda Ara').OdaSec('PAHALIODA').get('mat-dialog-container',{timeout:60000}).contains('İptal').click({force:true})
            .AdresBilgileri('Jack','Sparrow','05454554545','jack@gmail.com','Antalya','07850','ucgen mah 6765sok no:6/5 Muratpaşa/Antalya','adresbilgileri')
                .get('mat-tab-header').contains('Yerinde Ödeme').click({force:true})
                    .get('mat-vertical-stepper').contains('Ödeme Bilgileri').parent().parent().find('mat-checkbox').find('.mat-checkbox-inner-container').click({force:true})
                        .tusTikla('Tamamla').get('circle',{timeout:60000}).should('exist',{timeout:60000}).get('circle',{timeout:60000}).should('not.exist',{timeout:60000})
                        .get('ta-pages-complete').contains('Rezervasyon Formu Sms Gönderildi',{timeout:60000})
                            .get('ta-pages-complete').contains('Rezervasyon Formu Mail Gönderildi',{timeout:60000})
        })
})